server:
  port: 8080

spring:
  application:
    name: service-gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: service-user
              uri: lb://SERVICE-USER
              predicates:
                - Path=/api/service-user/**
              filters:
                - StripPrefix=2
            - id: service-item
              uri: lb://SERVICE-ITEM
              predicates:
                - Path=/api/service-item/**
              filters:
                - StripPrefix=2
            - id: service-order
              uri: lb://SERVICE-ORDER
              predicates:
                - Path=/api/service-order/**
              filters:
                - StripPrefix=2
            - id: service-ai
              uri: lb://SERVICE-AI
              predicates:
                - Path=/api/service-ai/**
              filters:
                - StripPrefix=2

jwt:
  secret: hyeonsang-jwt-security

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true