server:
  port: 8083

spring:
  application:
    name: service-order
  datasource:
    url: jdbc:h2:mem:orderdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  kafka:
    bootstrap-servers: localhost:9092
    listener:
      observation-enabled: true
    template:
      observation-enabled: true
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: >
          OrderCreatedEvent:com.example.service_order.event.OrderCreatedEvent,
          OrderCancelledEvent:com.example.service_order.event.OrderCancelledEvent,
          CompensateStockDecreaseEvent:com.example.service_order.event.CompensateStockDecreaseEvent,
          OrderStatusUpdateFailedEvent:com.example.service_order.event.OrderStatusUpdateFailedEvent
    consumer:
      group-id: order-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.type.mapping: >
          StockDecreasedEvent:com.example.service_order.event.StockDecreasedEvent,
          StockDecreaseFailedEvent:com.example.service_order.event.StockDecreaseFailedEvent,
          StockIncreasedEvent:com.example.service_order.event.StockIncreasedEvent,
          OrderProcessingFailedEvent:com.example.service_order.event.OrderProcessingFailedEvent,
          CancelProcessingFailedEvent:com.example.service_order.event.CancelProcessingFailedEvent

management:
  tracing:
    sampling:
      probability: 1.0
    propagation:
      consume: B3
      produce: B3
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

logging:
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'
